package com.lladlam.melox.core.network
import com.lladlam.melox.core.account.NeteaseSessionStore
import com.lladlam.melox.core.model.SearchSong
import java.io.IOException
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import okhttp3.OkHttpClient
import org.json.JSONArray
import org.json.JSONObject

data class MeloXAlbumSummary(val id: Long, val name: String, val artworkUrl: String?, val artistText: String, val type: String?)
data class MeloXAlbumDetail(val album: MeloXAlbumSummary, val description: String?, val songs: List<SearchSong>, val subscribed: Boolean?)
data class MeloXArtistDetail(val id: Long, val name: String, val artworkUrl: String?, val aliases: List<String>, val hotSongs: List<SearchSong>, val albums: List<MeloXAlbumSummary>)
class NeteaseCollectionDetailsClient(cookieProvider: () -> String, httpClient: OkHttpClient = OkHttpClient()) {
    private val cookieProvider = cookieProvider; private val eapi = NeteaseAuthenticatedEapi(cookieProvider, httpClient); private val weapi = NeteaseAuthenticatedWeapi(cookieProvider, httpClient)
    suspend fun albumDetail(id: Long): MeloXAlbumDetail = withContext(Dispatchers.IO) { val logged = NeteaseSessionStore.containsMusicU(cookieProvider()); val r = eapi.post("/api/v1/album/$id", authenticated = logged); val obj = r.optJSONObject("album") ?: throw IOException("网易云没有返回专辑信息"); val album = parseAlbum(obj) ?: throw IOException("无法解析专辑"); val songs = parseSongs(r.optJSONArray("songs")); val sub = if (logged) runCatching { val data = JSONObject().put("id", id); val d = try { weapi.post("/api/album/detail/dynamic", data) } catch (e: IOException) { if (!e.message.orEmpty().contains("空响应")) throw e; eapi.post("/api/album/detail/dynamic", data) }; d.optBoolean("isSub", false) }.getOrNull() else null; MeloXAlbumDetail(album, obj.optString("description").takeIf(String::isNotBlank) ?: obj.optString("briefDesc").takeIf(String::isNotBlank), songs, sub) }
    suspend fun setAlbumSubscribed(id: Long, subscribed: Boolean) = withContext(Dispatchers.IO) { val path = if (subscribed) "/api/album/sub" else "/api/album/unsub"; val data = JSONObject().put("id", id); try { weapi.post(path, data) } catch (e: IOException) { if (!e.message.orEmpty().contains("空响应")) throw e; eapi.post(path, data) }; Unit }
    suspend fun artistDetail(id: Long): MeloXArtistDetail = withContext(Dispatchers.IO) { val logged = NeteaseSessionStore.containsMusicU(cookieProvider()); val detail = eapi.post("/api/v1/artist/$id", authenticated = logged); val a = detail.optJSONObject("artist") ?: throw IOException("网易云没有返回歌手信息"); val ar = eapi.post("/api/artist/albums/$id", JSONObject().put("limit", 100).put("offset", 0).put("total", true), logged); val aliasesJson = a.optJSONArray("alias") ?: JSONArray(); val aliases = buildList { for (i in 0 until aliasesJson.length()) aliasesJson.optString(i).takeIf(String::isNotBlank)?.let(::add) }; val albumsJson = ar.optJSONArray("hotAlbums") ?: JSONArray(); val albums = buildList { for (i in 0 until albumsJson.length()) parseAlbum(albumsJson.optJSONObject(i))?.let(::add) }; MeloXArtistDetail(a.optLong("id", id), a.optString("name").ifBlank { "未知歌手" }, secure(a.optString("picUrl").takeIf(String::isNotBlank) ?: a.optString("img1v1Url").takeIf(String::isNotBlank)), aliases, parseSongs(detail.optJSONArray("hotSongs")), albums) }
    private fun parseSongs(values: JSONArray?): List<SearchSong> = buildList { val s = values ?: JSONArray(); for (i in 0 until s.length()) parseSong(s.optJSONObject(i))?.let(::add) }
    private fun parseAlbum(v: JSONObject?): MeloXAlbumSummary? { v ?: return null; val id = v.optLong("id", -1L); if (id <= 0L) return null; val aa = v.optJSONArray("artists") ?: v.optJSONArray("ar") ?: JSONArray(); val artists = buildList { for (i in 0 until aa.length()) aa.optJSONObject(i)?.optString("name")?.takeIf(String::isNotBlank)?.let(::add) }.joinToString(" / "); return MeloXAlbumSummary(id, v.optString("name").ifBlank { "未命名专辑" }, secure(v.optString("picUrl").takeIf(String::isNotBlank) ?: v.optString("blurPicUrl").takeIf(String::isNotBlank)), artists.ifBlank { v.optJSONObject("artist")?.optString("name").orEmpty().ifBlank { "未知歌手" } }, v.optString("type").takeIf(String::isNotBlank)) }
    private fun parseSong(v: JSONObject?): SearchSong? { v ?: return null; val id = v.optLong("id", -1L); if (id <= 0L) return null; val aa = v.optJSONArray("ar") ?: v.optJSONArray("artists") ?: JSONArray(); val artists = buildList { for (i in 0 until aa.length()) aa.optJSONObject(i)?.optString("name")?.takeIf(String::isNotBlank)?.let(::add) }.joinToString(" / "); val al = v.optJSONObject("al") ?: v.optJSONObject("album"); return SearchSong(id, v.optString("name").ifBlank { "未知歌曲" }, artists.ifBlank { "未知歌手" }, al?.optString("name").orEmpty(), secure(al?.optString("picUrl")?.takeIf(String::isNotBlank) ?: al?.optString("blurPicUrl")?.takeIf(String::isNotBlank)), v.optLong("dt", v.optLong("duration", 0L)).coerceAtLeast(0L)) }
    private fun secure(v: String?): String? = v?.let { if (it.startsWith("http://", true)) "https://${it.substringAfter("://")}" else it }
}
